blank_issues_enabled: false
contact_links:
  - name: Questions or Discussions
    url: https://github.com/yogeshpaliyal/awesome-android-tooling/discussions
    about: Please ask and answer questions here.